grid_map_filters:

  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter

  # # Duplicate layer.
  # - name: duplicate
  #   type: gridMapFilters/DuplicationFilter
  #   params:
  #     input_layer: ...
  #     output_layer: ...

  # Delete color layer.
  # - name: delete_original_layers
  #   type: gridMapFilters/DeletionFilter
  #   params:
  #     layers: [color] # List of layers.

  # Fill holes in the map with inpainting.
  - name: inpaint
    type: gridMapCv/InpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 0.05

  # Reduce noise with a radial blurring filter.
  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: elevation_inpainted
      output_layer: elevation_smooth
      radius: 0.06

  # Boxblur as an alternative to the inpaint and radial blurring filter above.
  # - name: boxblur
  #   type: gridMapFilters/SlidingWindowMathExpressionFilter
  #   params:
  #     input_layer: elevation
  #     output_layer: elevation_smooth
  #     expression: meanOfFinites(elevation)
  #     compute_empty_cells: true
  #     edge_handling: crop # options: inside, crop, empty, mean
  #     window_size: 5 # optional

  # Compute surface normals.
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation_inpainted
      output_layers_prefix: normal_vectors_
      radius: 0.051 # this must be larger than resolution (rounding errors lead to crashes)
      normal_vector_positive_axis: z
      edge_handling: crop # options: inside, crop, empty, mean

  # Add a color layer for visualization based on the surface normal.
  #- name: normal_color_map
  #  type: gridMapFilters/NormalColorMapFilter
  #  params:
  #    input_layers_prefix: normal_vectors_
  #    output_layer: normal_color

  # Compute slope from surface normal.
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_vectors_z)

  # Compute roughness as absolute difference from map to smoothened map.
  - name: roughness
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: roughness
      expression: abs(elevation_inpainted - elevation_smooth)

  # Edge detection by computing the standard deviation from slope.
  - name: edge_detection
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: slope
      output_layer: edges
      expression: sqrt(sumOfFinites(square(slope - meanOfFinites(slope))) ./ numberOfFinites(slope)) # Standard deviation
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.125 # using 2.5 times the resolution (usually 2.5*0.02 for ANYmal realsense maps, but using 2.5*0.05 for FSC)

  # # Edge detection on elevation layer with convolution filter as alternative to filter above.
  # - name: edge_detection
  #   type: gridMapFilters/SlidingWindowMathExpressionFilter
  #   params:
  #     input_layer: elevation_inpainted
  #     output_layer: edges
  #     expression: 'sumOfFinites([0,1,0;1,-4,1;0,1,0].*elevation_inpainted)' # Edge detection.
  #     # expression: 'sumOfFinites([0,-1,0;-1,5,-1;0,-1,0].*elevation_inpainted)' # Sharpen.
  #     compute_empty_cells: false
  #     edge_handling: mean # options: inside, crop, empty, mean
  #     window_size: 3 # Make sure to make this compatible with the kernel matrix.

  # Compute traversability as normalized weighted sum of slope and roughness.
  - name: traversability
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: 0.5 * (1.0 - (slope / 0.6)) + 0.5 * (1.0 - (roughness / 0.1))

  # Set lower threshold on traversability.
  - name: traversability_lower_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: traversability
      lower_threshold: 0.0
      set_to: 0.0

  # Set upper threshold on traversability.
  - name: traversability_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: traversability
      upper_threshold: 1.0
      set_to: 1.0 # Other uses: .nan, .inf

  # Duplicate layer.
  - name: traversability_clean
    type: gridMapFilters/DuplicationFilter
    params:
      input_layer: traversability
      output_layer: traversability_clean

  #################################################################
  # Aggregate stats for a worst-case analysis of footholds

  # slope
  - name: foot_slope
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: slope
      output_layer: foot_slope
      expression: maxOfFinites(slope)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.10
  - name: bestcase_foot_slope
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_slope
      output_layer: bestcase_foot_slope
      expression: minOfFinites(foot_slope)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30
  - name: worstcase_foot_slope
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_slope
      output_layer: worstcase_foot_slope
      expression: maxOfFinites(foot_slope)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30

  # height difference
  - name: foot_hdiff
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: elevation
      output_layer: foot_hdiff
      expression: maxOfFinites(elevation) - minOfFinites(elevation)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.10
  - name: bestcase_foot_hdiff
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_hdiff
      output_layer: bestcase_foot_hdiff
      expression: minOfFinites(foot_hdiff)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30
  - name: worstcase_foot_hdiff
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_hdiff
      output_layer: worstcase_foot_hdiff
      expression: maxOfFinites(foot_hdiff)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30

  # edges
  - name: foot_edges
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: edges
      output_layer: foot_edges
      expression: maxOfFinites(edges)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.10
  - name: bestcase_foot_edges
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_edges
      output_layer: bestcase_foot_edges
      expression: minOfFinites(foot_edges)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30

  # incompleteness
  - name: foot_incompleteness
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: elevation
      output_layer: foot_incompleteness
      expression: 1 - ( numberOfFinites(elevation) / 4 )
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.10
  - name: bestcase_foot_incompleteness
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_incompleteness
      output_layer: bestcase_foot_incompleteness
      expression: minOfFinites(foot_incompleteness)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30
  - name: worstcase_foot_incompleteness
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_incompleteness
      output_layer: worstcase_foot_incompleteness
      expression: maxOfFinites(foot_incompleteness)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30

  # controller steps
  - name: worstcase_foot_edges
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_edges
      output_layer: worstcase_foot_edges
      expression: maxOfFinites(foot_edges)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.30
  - name: robot_controller_unfeasibility_steps
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: foot_edges
      output_layer: robot_controller_unfeasibility_steps
      expression: maxOfFinites(foot_edges)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.20
  - name: controller_steps_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: robot_controller_unfeasibility_steps
      upper_threshold: 0.65
      set_to: 1.0

  # controller trot
  - name: robot_controller_unfeasibility_trot
    type: gridMapFilters/SlidingWindowMathExpressionFilter
    params:
      input_layer: worstcase_foot_edges
      output_layer: robot_controller_unfeasibility_trot
      expression: maxOfFinites(worstcase_foot_edges)
      compute_empty_cells: false
      edge_handling: crop # options: inside, crop, empty, mean
      window_length: 0.20
  - name: controller_trot_upper_threshold
    type: gridMapFilters/ThresholdFilter
    params:
      layer: robot_controller_unfeasibility_trot
      upper_threshold: 0.15
      set_to: 1.0

